"""Exact authored-part census before export; historical display labels are not ownership filters."""
from collections import Counter


def normalize_part_id(value):
    """Normalize the known historical label once, preserving the actual authored identifier."""
    return value.removeprefix('PROPOSAL | ') if isinstance(value, str) else ''


def require_part_census(observed, expected, model):
    """Raise before any writer if an authored part is omitted, duplicated, unexpected or from another model.

    observed contains one identifier per selected OBJECT; expected is the independent approved part inventory,
    not another list generated by the same selection predicate. Shared props are counted separately by callers.
    """
    raw_observed=list(observed); raw_expected=list(expected)
    actual=Counter(normalize_part_id(p) for p in raw_observed)
    wanted=Counter(normalize_part_id(p) for p in raw_expected)
    invalid=[p for p in [*actual,*wanted] if not p.startswith(model+'/')]
    missing=sorted(set(wanted)-set(actual)); unexpected=sorted(set(actual)-set(wanted))
    duplicates=sorted(p for p,n in actual.items() if n!=1)
    expected_duplicates=sorted(p for p,n in wanted.items() if n!=1)
    if not wanted or invalid or missing or unexpected or duplicates or expected_duplicates:
        raise ValueError(f'{model} authored part census failed: missing={missing}, unexpected={unexpected}, '
                         f'duplicates={duplicates}, expected_duplicates={expected_duplicates}, invalid={invalid}')
    return dict(status='PASS',model=model,count=len(actual),
                normalized_historical_labels=sum(p!=normalize_part_id(p) for p in raw_observed),
                missing=[],unexpected=[],duplicates=[])
