// zzKoreanConstructionTest - Korean construction/destruction test map (owner request 2026-10-08).
// Spine and bench GENERATED by scripts/tools/unitbench.py (do not edit those parts); only the marked block at the
// end is hand-written: three TEST Korean Builder Wagons beside player 1's Town Center and test resources.
// Variant grid: 4 subjects in rows of 4 around the map centre, subject 1 = front row, left
// (screen view of the editor camera); control unit House in front, centred; players on a 0.42 ring:
//   1  zpKoreanTownCenterTest   row 1 of 1 counted from the front, column 1 from the left
//   2  zzKoreanBarracksPhysics  row 1 of 1 counted from the front, column 2 from the left
//   3  zzKoreanStablePhysics    row 1 of 1 counted from the front, column 3 from the left
//   4  zzTESTKoreanBuilderWagon row 1 of 1 counted from the front, column 4 from the left
// The spine (includes, chooseMercs, rmSetMapSize, rmTerrainInitialize, rmSetMapType, player placement, TC)
// is copied from scripts/maps/000_hkt_test.xs (commit 7130e597) and is mandatory: without it generation
// crashes (0xC0000005 +0x7E9D2D) and without chooseMercs() it aborts (+0xA7508D).

include "mercenaries.xs";
include "ypAsianInclude.xs";
include "ypKOTHInclude.xs";

void main(void)
{
   rmSetStatusText("", 0.01);
   rmSetMapSize(200, 200);
   rmSetMapElevationHeightBlend(1);
   rmSetSeaLevel(0.0);
   rmSetLightingSet("sonora_skirmish");
   rmSetMapElevationParameters(cElevTurbulence, 0.02, 2, 0.5, 1.0);
   rmSetBaseTerrainMix("africa desert rock");
   rmTerrainInitialize("deccan\ground_grass3_deccan", 1.0);
   rmSetMapType("arabia");
   rmSetMapType("desert");
   chooseMercs();
   rmSetWorldCircleConstraint(true);
   rmDefineClass("player");
   rmSetStatusText("", 0.30);

   // players: a small ring so player 1 (the human) is near the centre and the camera opens on it
   rmSetPlacementSection(0.0, 1.0);
   rmPlacePlayersCircular(0.42, 0.42, 0.0);
   rmSetStatusText("", 0.50);

   int tcID = rmCreateObjectDef("player TC");
   rmAddObjectDefItem(tcID, "TownCenter", 1, 0.0);
   rmSetObjectDefMinDistance(tcID, 0.0);
   rmSetObjectDefMaxDistance(tcID, 0.0);
   for(i=1; <= cNumberNonGaiaPlayers)
   {
      rmPlaceObjectDefAtLoc(tcID, i, rmPlayerLocXFraction(i), rmPlayerLocZFraction(i));
   }

   // the bench: 4 subjects in rows of 4 around the map centre (40 m apart, rows 44 m apart
   // along x + z, the camera's depth axis), control House in front, player 1, fixed positions
   int benchControlID = rmCreateObjectDef("bench control");
   rmAddObjectDefItem(benchControlID, "House", 1, 0.0);
   rmSetObjectDefMinDistance(benchControlID, 0.0);
   rmSetObjectDefMaxDistance(benchControlID, 0.0);
   rmPlaceObjectDefAtLoc(benchControlID, 1, 0.5 - rmXMetersToFraction(21.2), 0.5 - rmZMetersToFraction(21.2));

   // subject 1: zpKoreanTownCenterTest (row 1 of 1 counted from the front, column 1 from the left)
   int benchSubject1ID = rmCreateObjectDef("bench subject 1");
   rmAddObjectDefItem(benchSubject1ID, "zpKoreanTownCenterTest", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubject1ID, 0.0);
   rmSetObjectDefMaxDistance(benchSubject1ID, 0.0);
   rmPlaceObjectDefAtLoc(benchSubject1ID, 1, 0.5 - rmXMetersToFraction(42.4), 0.5 + rmZMetersToFraction(42.4));

   // subject 2: zzKoreanBarracksPhysics (row 1 of 1 counted from the front, column 2 from the left)
   int benchSubject2ID = rmCreateObjectDef("bench subject 2");
   rmAddObjectDefItem(benchSubject2ID, "zzKoreanBarracksPhysics", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubject2ID, 0.0);
   rmSetObjectDefMaxDistance(benchSubject2ID, 0.0);
   rmPlaceObjectDefAtLoc(benchSubject2ID, 1, 0.5 - rmXMetersToFraction(14.1), 0.5 + rmZMetersToFraction(14.1));

   // subject 3: zzKoreanStablePhysics (row 1 of 1 counted from the front, column 3 from the left)
   int benchSubject3ID = rmCreateObjectDef("bench subject 3");
   rmAddObjectDefItem(benchSubject3ID, "zzKoreanStablePhysics", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubject3ID, 0.0);
   rmSetObjectDefMaxDistance(benchSubject3ID, 0.0);
   rmPlaceObjectDefAtLoc(benchSubject3ID, 1, 0.5 + rmXMetersToFraction(14.1), 0.5 - rmZMetersToFraction(14.1));

   // subject 4: zzTESTKoreanBuilderWagon (row 1 of 1 counted from the front, column 4 from the left)
   int benchSubject4ID = rmCreateObjectDef("bench subject 4");
   rmAddObjectDefItem(benchSubject4ID, "zzTESTKoreanBuilderWagon", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubject4ID, 0.0);
   rmSetObjectDefMaxDistance(benchSubject4ID, 0.0);
   rmPlaceObjectDefAtLoc(benchSubject4ID, 1, 0.5 + rmXMetersToFraction(42.4), 0.5 - rmZMetersToFraction(42.4));

   // --- hand-written addition (Korean construction test): builders and resources for player 1 -------------------
   // The pre-built Korean TC, Barracks and Stable above are for destruction tests (select one, Delete).
   // The TEST Korean Builder Wagons build new ones slowly (about 3-4 minutes) to show every construction stage.
   int koreanBuildersID = rmCreateObjectDef("korean test builders");
   rmAddObjectDefItem(koreanBuildersID, "zzTESTKoreanBuilderWagon", 3, 4.0);
   rmSetObjectDefMinDistance(koreanBuildersID, 12.0);
   rmSetObjectDefMaxDistance(koreanBuildersID, 16.0);
   rmPlaceObjectDefAtLoc(koreanBuildersID, 1, rmPlayerLocXFraction(1), rmPlayerLocZFraction(1));
   rmAddPlayerResource(1, "Wood", 20000);
   rmAddPlayerResource(1, "Food", 10000);
   rmAddPlayerResource(1, "Gold", 10000);

   rmSetStatusText("", 1.0);
}
