"""Unit visual test bench: generate the most basic map with ONE unit under test, safely.

    python scripts/tools/unitbench.py --proto zpSPCLondonBasilica
    python scripts/tools/unitbench.py --proto zpSPCLondonBasilica --control House --dist 24 --owner 1
    python scripts/tools/unitbench.py --proto House --stem 000_unitbench_ctl      # control-only run
    python scripts/tools/unitbench.py --proto X --out C:/some/dir --json report.json --no-preflight
    python scripts/tools/unitbench.py --proto zzA,zzB,zzC,zzD --stem 000_bonebench     # variant grid, one map

What it writes: <stem>.xs + <stem>.xml into the Steam install's Game/RandMaps (the Scenario Editor
re-reads them on every File > New; never into the mod folder unless --out says so).

Several comma-separated --proto names = a VARIANT GRID: one generation shows every variant side by side
instead of one game restart per variant. Rows of --cols subjects, --spacing m apart, --rowgap m between
rows (44 m keeps a 26 m tall building from hiding the row behind it), centred on the map centre where the
editor camera opens; the rows run along (x - z), which is screen-horizontal there (+x runs up-right: bench
shot 2026-09-17). Subject 1 = front row, left; numbering runs left to right, front to back. The players
move to a 0.42 ring so their Town Centers stay out of the picture; the control stands in front, centred.

Why the bench crashed before (evidence in scripts/maps/000_hkt_test.xs, commit 7130e597, and the
map-minimap skill): (1) a stripped spine - missing rmSetMapSize / rmTerrainInitialize / player
placement dies at 0xC0000005 +0x7E9D2D; (2) missing includes + chooseMercs() - a Saloon's train list is
built from the mercenary set at world creation, generation aborted at +0xA7508D; (3) a proto whose
animfile / model / material / texture does not resolve, or an LF-only art XML (renders nothing).
This tool freezes the spine in a template that is never edited by hand, substitutes only the proto
names, self-checks the spine in its own output, and runs an offline pre-flight for (3) before the
game is touched. A vanilla control unit stands beside the subject so a crash is attributable.

Pre-flight (offline, no game needed):
  P1 proto exists      data/protomods.xml, else the live Data.bar protoy (never the repo snapshot)
  P2 animfile resolves mod art/ first, then the archives
  P3 model + material  every <file> in the animfile -> .gr2 and .material (mod or archives)
  P4 textures          material <texture override> and animfile <texture> -> .ddt (mod or archives)
  P5 art XML is CRLF   LF-only animfile/material = unit places, model never renders (hard rule)
  P6 mapcheck static   on the generated script; the stale-snapshot S4 for a proto verified in P1
                       is downgraded to a note
  P7 spine self-check  every mandatory spine line is present in the generated text

Exit 0 = written (pre-flight clean or --no-preflight), 1 = pre-flight FAIL (nothing written unless
--force), 2 = usage error. The JSON report (--json) is what rm-unit-bench and bench_run.py consume.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / ".claude" / "skills" / "aoe3de-bar-archives" / "scripts"))
sys.dont_write_bytecode = True

BS = chr(92)

XS_TEMPLATE = """// {STEM} - unit visual test bench. GENERATED by scripts/tools/unitbench.py - do not edit by hand.
{LAYOUT}
// The spine (includes, chooseMercs, rmSetMapSize, rmTerrainInitialize, rmSetMapType, player placement, TC)
// is copied from scripts/maps/000_hkt_test.xs (commit 7130e597) and is mandatory: without it generation
// crashes (0xC0000005 +0x7E9D2D) and without chooseMercs() it aborts (+0xA7508D).

include "mercenaries.xs";
include "ypAsianInclude.xs";
include "ypKOTHInclude.xs";

void main(void)
{
   rmSetStatusText("", 0.01);
   rmSetMapSize(200, 200);
   rmSetMapElevationHeightBlend(1);
   rmSetSeaLevel(0.0);
   rmSetLightingSet("sonora_skirmish");
   rmSetMapElevationParameters(cElevTurbulence, 0.02, 2, 0.5, 1.0);
   rmSetBaseTerrainMix("africa desert rock");
   rmTerrainInitialize("deccan{BS}ground_grass3_deccan", 1.0);
   rmSetMapType("arabia");
   rmSetMapType("desert");
   chooseMercs();
   rmSetWorldCircleConstraint(true);
   rmDefineClass("player");
   rmSetStatusText("", 0.30);

   // players: a small ring so player 1 (the human) is near the centre and the camera opens on it
   rmSetPlacementSection(0.0, 1.0);
   rmPlacePlayersCircular({RING}, {RING}, 0.0);
   rmSetStatusText("", 0.50);

   int tcID = rmCreateObjectDef("player TC");
   rmAddObjectDefItem(tcID, "TownCenter", 1, 0.0);
   rmSetObjectDefMinDistance(tcID, 0.0);
   rmSetObjectDefMaxDistance(tcID, 0.0);
   for(i=1; <= cNumberNonGaiaPlayers)
   {
      rmPlaceObjectDefAtLoc(tcID, i, rmPlayerLocXFraction(i), rmPlayerLocZFraction(i));
   }

{BENCH}
   rmSetStatusText("", 1.0);
}
"""

LAYOUT_SINGLE = """// Player {OWNER} starts at the map centre; two units stand {DIST} m away on the x axis:
//   control unit {CONTROL} (east, +x)   unit under test {PROTO} (west, -x)"""

LAYOUT_GRID = """// Variant grid: {N} subjects in rows of {COLS} around the map centre, subject 1 = front row, left
// (screen view of the editor camera); control unit {CONTROL} in front, centred; players on a 0.42 ring:
{LIST}"""

BENCH_SINGLE = """   // the bench: control (vanilla, known to render) and subject, player {OWNER}, fixed positions
   int benchControlID = rmCreateObjectDef("bench control");
   rmAddObjectDefItem(benchControlID, "{CONTROL}", 1, 0.0);
   rmSetObjectDefMinDistance(benchControlID, 0.0);
   rmSetObjectDefMaxDistance(benchControlID, 0.0);
   int benchSubjectID = rmCreateObjectDef("bench subject");
   rmAddObjectDefItem(benchSubjectID, "{PROTO}", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubjectID, 0.0);
   rmSetObjectDefMaxDistance(benchSubjectID, 0.0);
   float px = rmPlayerLocXFraction(1);
   float pz = rmPlayerLocZFraction(1);
   float dx = rmXMetersToFraction({DIST});
   rmPlaceObjectDefAtLoc(benchControlID, {OWNER}, px + dx, pz);
   rmPlaceObjectDefAtLoc(benchSubjectID, {OWNER}, px - dx, pz);
"""

BENCH_GRID_HEAD = """   // the bench: {N} subjects in rows of {COLS} around the map centre ({SPACING} m apart, rows {ROWGAP} m apart
   // along x + z, the camera's depth axis), control {CONTROL} in front, player {OWNER}, fixed positions
   int benchControlID = rmCreateObjectDef("bench control");
   rmAddObjectDefItem(benchControlID, "{CONTROL}", 1, 0.0);
   rmSetObjectDefMinDistance(benchControlID, 0.0);
   rmSetObjectDefMaxDistance(benchControlID, 0.0);
   rmPlaceObjectDefAtLoc(benchControlID, {OWNER}, {CX}, {CZ});
"""

BENCH_GRID_SUBJECT = """   // subject {I}: {PROTO} ({SLOT})
   int benchSubject{I}ID = rmCreateObjectDef("bench subject {I}");
   rmAddObjectDefItem(benchSubject{I}ID, "{PROTO}", 1, 0.0);
   rmSetObjectDefMinDistance(benchSubject{I}ID, 0.0);
   rmSetObjectDefMaxDistance(benchSubject{I}ID, 0.0);
   rmPlaceObjectDefAtLoc(benchSubject{I}ID, {OWNER}, {X}, {Z});
"""

XML_TEMPLATE = """<?xml version = "1.0" encoding = "UTF-8"?>
<mapinfo displayName = "{STEM}" detailsText = "{DETAILS} Generated by scripts/tools/unitbench.py."
    imagepath = "ui{BS}random_map{BS}atols{BS}atols_mini" cannotReplace = "" loadBackground = "ui{BS}random_map{BS}atols{BS}atols_map">
   <loadss>ui{BS}random_map{BS}atols{BS}atols_01</loadss>
</mapinfo>
"""

# every one of these must survive in the generated script (P7)
SPINE = [
    'include "mercenaries.xs";', 'include "ypAsianInclude.xs";', 'include "ypKOTHInclude.xs";',
    "void main(void)", "rmSetMapSize(200, 200);", "rmSetSeaLevel(0.0);", "rmSetBaseTerrainMix(",
    "rmTerrainInitialize(", 'rmSetMapType("arabia");', "chooseMercs();", "rmPlacePlayersCircular(",
    'rmAddObjectDefItem(tcID, "TownCenter", 1, 0.0);', "rmPlaceObjectDefAtLoc(tcID, i,",
    "rmPlaceObjectDefAtLoc(benchControlID,",
]
SPINE_SINGLE = ["rmPlaceObjectDefAtLoc(benchSubjectID,"]

DEFAULT_OUT = Path(r"C:\Program Files (x86)\Steam\steamapps\common\AoE3DE\Game\RandMaps")


# --------------------------------------------------------------------------- archive + mod lookups
class Assets:
    """Existence checks against the mod tree (art/, data/) and the archive index, case-insensitive."""

    def __init__(self):
        self.mod = {}
        for root in ("art", "data"):
            base = REPO / root
            if base.is_dir():
                for dp, _dn, fns in os.walk(base):
                    for fn in fns:
                        rel = os.path.relpath(os.path.join(dp, fn), REPO).replace("/", BS).lower()
                        self.mod[rel] = Path(dp) / fn
        self.bt = None
        self.index = None
        self.arch = None

    def _load_archive(self):
        if self.index is not None:
            return
        import bartool
        self.bt = bartool
        self.index = bartool.build_index(bartool.find_game_dir())
        self.arch = {}
        entries = self.index.values() if isinstance(self.index, dict) else self.index
        for e in entries:
            p = getattr(e, "path", None) or getattr(e, "name", None) or str(e)
            self.arch[str(p).replace("/", BS).lower()] = e

    def mod_path(self, rel):
        return self.mod.get(rel.replace("/", BS).lower())

    def in_archive(self, rel):
        self._load_archive()
        key = rel.replace("/", BS).lower()
        return key in self.arch or (key + ".xmb") in self.arch

    def archive_text(self, rel):
        self._load_archive()
        key = rel.replace("/", BS).lower()
        e = self.arch.get(key) or self.arch.get(key + ".xmb")
        if e is None:
            return None
        data, _dec = self.bt.decode(self.bt.read_entry(e), True)
        return data.decode("utf-8", "ignore")

    def exists_any(self, candidates):
        for c in candidates:
            if self.mod_path(c) is not None or self.in_archive(c):
                return c
        return None


def lf_only(path: Path) -> bool:
    b = path.read_bytes()
    return b"\n" in b and b"\r\n" not in b


# --------------------------------------------------------------------------- pre-flight
def find_proto(name, assets):
    pm = (REPO / "data" / "protomods.xml").read_text(encoding="utf-8", errors="ignore")
    m = re.search(r'<unit id="(\d+)" name="' + re.escape(name) + r'">(.*?)</unit>', pm, re.S)
    if m:
        return "mod", m.group(2)
    live = assets.archive_text("Data" + BS + "protoy.xml")
    if live:
        m = re.search(r'<unit id="(\d+)" name="' + re.escape(name) + r'">(.*?)</unit>', live, re.S)
        if m:
            return "vanilla", m.group(2)
    return None, None


def preflight(protos, control, dist, xs_path, spacing=None):
    if isinstance(protos, str):
        protos = [protos]
    rep = {"proto": ",".join(protos), "control": control, "checks": [], "fail": 0, "warn": 0}
    assets = Assets()

    def add(code, status, msg):
        rep["checks"].append({"check": code, "status": status, "msg": msg})
        if status == "FAIL":
            rep["fail"] += 1
        elif status == "WARN":
            rep["warn"] += 1
        print(f"  {code} {status:4s} {msg}")

    verified = set()
    subjects = [("subject", protos[0])] if len(protos) == 1 else [(f"subject {i}", p) for i, p in enumerate(protos, 1)]
    for tag, name in subjects + [("control", control)]:
        src, rec = find_proto(name, assets)
        if not src:
            add("P1", "FAIL", f"{tag} proto {name!r} not in protomods nor in the live Data.bar protoy")
            continue
        verified.add(name)
        add("P1", "OK", f"{tag} proto {name!r} found in {src}")
        anim = re.search(r"<animfile>([^<]+)</animfile>", rec or "")
        ox = re.search(r"<obstructionradiusx>([\d.]+)", rec or "")
        oz = re.search(r"<obstructionradiusz>([\d.]+)", rec or "")
        if ox and oz and tag.startswith("subject"):
            r = max(float(ox.group(1)), float(oz.group(1)))
            if len(protos) > 1:
                if spacing is not None and spacing < 2 * r + 4.0:
                    add("P1", "WARN", f"--spacing {spacing} m may overlap neighbours: {tag} obstruction radius {r} m; use --spacing {int(2 * r + 4) + 2}")
            elif dist < r + 8.0:
                add("P1", "WARN", f"--dist {dist} m may overlap the Town Center: subject obstruction radius {r} m (+~6 m TC); use --dist {int(r + 8) + 2}")
        if not anim:
            add("P2", "WARN", f"{tag}: no <animfile> in the record (icon-only or abstract proto?)")
            continue
        animrel = anim.group(1).strip()
        mod_anim = assets.mod_path("art" + BS + animrel)
        if mod_anim is not None:
            add("P2", "OK", f"{tag} animfile in mod: art{BS}{animrel}")
            text = mod_anim.read_bytes().decode("utf-8", "ignore")
            if lf_only(mod_anim):
                add("P5", "FAIL", f"{tag} animfile is LF-only (engine ignores it, model never renders): {mod_anim.name}")
            else:
                add("P5", "OK", f"{tag} animfile is CRLF")
        elif assets.in_archive("Art" + BS + animrel):
            add("P2", "OK", f"{tag} animfile in archives: Art{BS}{animrel}")
            text = assets.archive_text("Art" + BS + animrel) or ""
        else:
            add("P2", "FAIL", f"{tag} animfile not found in mod art/ nor archives: {animrel}")
            continue
        files = sorted(set(f.strip() for f in re.findall(r"<file>([^<]+)</file>", text)))
        for f in files:
            if f.lower().endswith('.particle'):
                particle = assets.exists_any(["art" + BS + f, "Art" + BS + f])
                add("P3", "OK" if particle else "FAIL", f"{tag} particle {f} " + ("found" if particle else "MISSING (mod art/ and archives)"))
                continue
            if ".pkfx" in f.lower():
                add("P3", "NOTE", f"{tag} particle effect {f} (PopcornFX, not a model; not checked)")
                continue
            gr2 = assets.exists_any(["art" + BS + f + ".gr2", "Art" + BS + f + ".gr2"])
            add("P3", "OK" if gr2 else "FAIL", f"{tag} model {f}.gr2 " + ("found" if gr2 else "MISSING (mod art/ and archives)"))
            mat_mod = assets.mod_path("art" + BS + f + ".material")
            mat_arch = assets.in_archive("Art" + BS + f + ".material")
            if mat_mod is None and not mat_arch:
                add("P3", "WARN", f"{tag} material {f}.material not found (the model may carry its own material)")
            else:
                add("P3", "OK", f"{tag} material {f}.material found in " + ("mod" if mat_mod else "archives"))
            if mat_mod is not None:
                if lf_only(mat_mod):
                    add("P5", "FAIL", f"{tag} material is LF-only (ignored by the engine): {mat_mod.name}")
                mtext = mat_mod.read_bytes().decode("utf-8", "ignore")
                for tex in sorted(set(re.findall(r'override="([^"]+)"', mtext))):
                    ok = assets.exists_any(["art" + BS + tex + ".ddt", "Art" + BS + tex + ".ddt",
                                            "art" + BS + tex + "_basecolor.ddt", "Art" + BS + tex + "_basecolor.ddt"])
                    add("P4", "OK" if ok else "FAIL", f"{tag} material texture {tex} " + ("found" if ok else "MISSING"))
        for tex in sorted(set(t.strip() for t in re.findall(r"<(?:texture|bumptexture|selectedtexture)>([^<]+)<", text))):
            ok = assets.exists_any(["art" + BS + tex + ".ddt", "Art" + BS + tex + ".ddt",
                                    "art" + BS + tex + "_basecolor.ddt", "Art" + BS + tex + "_basecolor.ddt"])
            add("P4", "OK" if ok else "WARN", f"{tag} animfile texture {tex} " + ("found" if ok else "not found (decal/selection textures are often engine-internal)"))

    # P6 mapcheck static on the generated script
    try:
        out = subprocess.run([sys.executable, "-m", "scripts.mapcheck", str(xs_path), "--static-only"],
                             cwd=str(REPO), capture_output=True, text=True, timeout=300).stdout
    except Exception as e:  # noqa: BLE001
        out = f"mapcheck could not run: {e}"
    fails = [l for l in out.splitlines() if l.startswith("FAIL")]
    for l in fails:
        m = re.search(r"unknown proto '([^']+)'", l)
        if m and m.group(1) in verified:
            add("P6", "NOTE", f"stale-snapshot S4 for {m.group(1)!r} (verified live in P1): " + l.strip()[:100])
        else:
            add("P6", "FAIL", l.strip()[:160])
    if not fails:
        add("P6", "OK", "mapcheck static: no FAIL")
    rep["mapcheck_tail"] = out.strip().splitlines()[-1:] if out else []
    return rep


# --------------------------------------------------------------------------- generate
def grid_slots(n, cols, spacing, rowgap):
    """(across, depth) metres of every subject from the map centre, front row first, left to right."""
    rows = (n + cols - 1) // cols
    slots = []
    for i in range(n):
        r, c = divmod(i, cols)
        in_row = min(cols, n - r * cols)
        slots.append(((c - (in_row - 1) / 2) * spacing, (r - (rows - 1) / 2) * rowgap, r + 1, c + 1))
    return slots, rows


def map_loc(across, depth):
    """Screen-horizontal = (x - z), camera depth = (x + z) -> XS fraction expressions around the centre."""
    k = 0.5 ** 0.5
    out = []
    for m, fn in (((across + depth) * k, "rmXMetersToFraction"), ((depth - across) * k, "rmZMetersToFraction")):
        out.append(f"0.5 + {fn}({m:.1f})" if m >= 0 else f"0.5 - {fn}({-m:.1f})")
    return out


def render(stem, protos, control, dist, owner, cols=3, spacing=36.0, rowgap=44.0):
    if isinstance(protos, str):
        protos = [protos]
    subs = {"STEM": stem, "CONTROL": control, "DIST": f"{float(dist):.1f}", "OWNER": str(owner), "BS": BS}
    if len(protos) == 1:
        subs["PROTO"] = protos[0]
        layout, bench, ring, spine = LAYOUT_SINGLE, BENCH_SINGLE, "0.12", SPINE + SPINE_SINGLE
        details = "Unit visual test bench: {PROTO} (west) beside control {CONTROL} (east), {DIST} m from player {OWNER}'s Town Center."
    else:
        slots, rows = grid_slots(len(protos), cols, spacing, rowgap)
        cx, cz = map_loc(0.0, min(s[1] for s in slots) - 30.0)
        bench = BENCH_GRID_HEAD.replace("{CX}", cx).replace("{CZ}", cz)
        lines, spine = [], list(SPINE)
        for i, (p, (across, depth, r, c)) in enumerate(zip(protos, slots), 1):
            x, z = map_loc(across, depth)
            slot = f"row {r} of {rows} counted from the front, column {c} from the left"
            bench += "\n" + (BENCH_GRID_SUBJECT.replace("{I}", str(i)).replace("{PROTO}", p)
                             .replace("{SLOT}", slot).replace("{X}", x).replace("{Z}", z))
            lines.append(f"//   {i}  {p:<24s} {slot}")
            spine.append(f"rmPlaceObjectDefAtLoc(benchSubject{i}ID,")
        for k, v in (("N", str(len(protos))), ("COLS", str(cols)), ("SPACING", f"{spacing:g}"), ("ROWGAP", f"{rowgap:g}")):
            bench = bench.replace("{" + k + "}", v)
        layout = LAYOUT_GRID.replace("{N}", str(len(protos))).replace("{COLS}", str(cols)).replace("{LIST}", "\n".join(lines))
        ring = "0.42"
        details = f"Unit variant grid: {', '.join(protos)} (subject 1 = front row, left), control {{CONTROL}} in front."
    xs = XS_TEMPLATE.replace("{LAYOUT}", layout).replace("{BENCH}", bench).replace("{RING}", ring)
    xml = XML_TEMPLATE.replace("{DETAILS}", details)
    for k, v in subs.items():
        xs = xs.replace("{" + k + "}", v)
        xml = xml.replace("{" + k + "}", v)
    missing = [s for s in spine if s not in xs]
    if missing:
        raise SystemExit(f"P7 spine self-check FAILED, refusing to write: {missing}")
    return xs.replace("\n", "\r\n"), xml.replace("\n", "\r\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--proto", required=True, help="unit under test (proto name); several comma-separated = variant grid")
    ap.add_argument("--cols", type=int, default=3, help="variant grid: subjects per row (default 3)")
    ap.add_argument("--spacing", type=float, default=36.0, help="variant grid: metres between subjects in a row (default 36)")
    ap.add_argument("--rowgap", type=float, default=44.0, help="variant grid: metres between rows (default 44)")
    ap.add_argument("--control", default="House", help="vanilla control unit placed beside it (default House)")
    ap.add_argument("--dist", type=float, default=24.0, help="metres from player 1's TC to each unit (default 24)")
    ap.add_argument("--owner", type=int, default=1, help="owning player of both units (default 1; 0 = Gaia)")
    ap.add_argument("--stem", default="000_unitbench", help="map file stem and editor display name")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output folder (default: Steam Game/RandMaps)")
    ap.add_argument("--json", default=None, help="write the pre-flight report here")
    ap.add_argument("--no-preflight", action="store_true")
    ap.add_argument("--force", action="store_true", help="write even if the pre-flight failed")
    a = ap.parse_args(argv)
    protos = [p.strip() for p in a.proto.split(",") if p.strip()]
    if not protos or not all(re.fullmatch(r"[A-Za-z0-9_]+", p) for p in protos + [a.control]):
        print("proto / control must be plain names", file=sys.stderr)
        return 2
    if len(set(protos)) != len(protos) or a.cols < 1:
        print("--proto names must be distinct and --cols >= 1", file=sys.stderr)
        return 2
    xs, xml = render(a.stem, protos, a.control, a.dist, a.owner, a.cols, a.spacing, a.rowgap)
    out = Path(a.out)
    xs_path, xml_path = out / f"{a.stem}.xs", out / f"{a.stem}.xml"
    tmp = REPO / "scripts" / "maps" / f"{a.stem}.xs"     # mapcheck needs a path; keep a repo copy for the record
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_bytes(xs.encode("utf-8"))
    (tmp.with_suffix(".xml")).write_bytes(xml.encode("utf-8"))
    print(f"[unitbench] {a.stem}: subject {a.proto}, control {a.control}, {a.dist} m, owner {a.owner}")
    rep = {"fail": 0, "warn": 0, "checks": []}
    if not a.no_preflight:
        print("[unitbench] pre-flight")
        rep = preflight(protos, a.control, a.dist, tmp, a.spacing)
    rep.update({"stem": a.stem, "xs": str(xs_path), "xml": str(xml_path), "repo_copy": str(tmp)})
    if a.json:
        Path(a.json).write_text(json.dumps(rep, indent=2), encoding="utf-8")
    if rep["fail"] and not a.force:
        print(f"[unitbench] PRE-FLIGHT FAILED ({rep['fail']} FAIL, {rep['warn']} WARN) - nothing written to {out}")
        return 1
    out.mkdir(parents=True, exist_ok=True)
    xs_path.write_bytes(xs.encode("utf-8"))
    xml_path.write_bytes(xml.encode("utf-8"))
    print(f"[unitbench] written {xs_path} and {xml_path} ({rep['fail']} FAIL, {rep['warn']} WARN)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
